/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {AutoController, ListFilter} from './ApiEndpoints'
import {AdminNavMenuItemIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {ApiList, getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
*/
export type AdminNavMenuItem = {
    title?: string,
    target?: string,
    iconRef?: string,
    visibilityRuleJson?: string,
}

/**
*/
export class AdminNavMenuItemApi extends AutoController<AdminNavMenuItem, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('adminnavmenuitem')
        this.includes = new AdminNavMenuItemIncludes('', '');
    }

    /**
      Overriden endpoint
      @param {filters} - Api.AvailableEndpoints.XmlDocMember
      @param {context} - Api.AvailableEndpoints.XmlDocMember

    */
    public list = (filters: ListFilter, includes: ApiIncludes[] = []): Promise<ApiList<AdminNavMenuItem>>  => {
        return getList<AdminNavMenuItem>(this.apiUrl + '/list'+ (includes.length != 0 ? '?includes=' + includes.map(include => include.toString()).join(', ') : ''), filters)
    }

}

export default new AdminNavMenuItemApi();
