/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {CategoryIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A category.
            These are the primary taxonomy mechanism; any site content can be grouped up in multiple categories.
*/
export type Category = VersionedContent<uint> & {
    name?: string,
    description?: string,
    featureRef?: string,
    iconRef?: string,
}

/**
*/
export class CategoryApi extends AutoController<Category, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('category')
        this.includes = new CategoryIncludes('', '');
    }

}

export default new CategoryApi();
