/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ComponentGroupIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A ComponentGroup
*/
export type ComponentGroup = VersionedContent<uint> & {
    name?: string,
    allowedComponents?: string,
    role: uint,
}

/**
*/
export class ComponentGroupApi extends AutoController<ComponentGroup, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('componentgroup')
        this.includes = new ComponentGroupIncludes('', '');
    }

}

export default new ComponentGroupApi();
