/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ConfigurationIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A Configuration entry in the database. Do not derive from this! 
            Use :Config instead when declaring the config options for your thing.
*/
export type Configuration = VersionedContent<uint> & {
    name?: string,
    environments?: string,
    key?: string,
    configJson?: string,
}

/**
*/
export class ConfigurationApi extends AutoController<Configuration, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('configuration')
        this.includes = new ConfigurationIncludes('', '');
    }

}

export default new ConfigurationApi();
