/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ContentFieldAccessRuleIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A ContentFieldAccessRule
*/
export type ContentFieldAccessRule = VersionedContent<uint> & {
    entityName?: string,
    isVirtualType: boolean,
    fieldName?: string,
    canRead?: string,
    canWrite?: string,
    roleId: uint,
}

/**
*/
export class ContentFieldAccessRuleApi extends AutoController<ContentFieldAccessRule, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('contentfieldaccessrule')
        this.includes = new ContentFieldAccessRuleIncludes('', '');
    }

}

export default new ContentFieldAccessRuleApi();
