/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {CustomContentTypeSelectOptionIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A CustomContentTypeSelectOption
*/
export type CustomContentTypeSelectOption = VersionedContent<uint> & {
    customContentTypeFieldId: uint,
    value?: string,
    order: uint,
}

/**
*/
export class CustomContentTypeSelectOptionApi extends AutoController<CustomContentTypeSelectOption, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('customcontenttypeselectoption')
        this.includes = new CustomContentTypeSelectOptionIncludes('', '');
    }

}

export default new CustomContentTypeSelectOptionApi();
