/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {CustomContentTypeFieldIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A custom content type field.
*/
export type CustomContentTypeField = VersionedContent<uint> & {
    customContentTypeId: uint,
    defaultValue?: string,
    dataType?: string,
    linkedEntity?: string,
    name?: string,
    nickName?: string,
    localised: boolean,
    urlEncoded: boolean,
    isHidden: boolean,
    hideSeconds: boolean,
    roundMinutes: boolean,
    validation?: string,
    order: uint,
    group?: string,
    optionsArePrices: boolean,
    deleted: boolean,
}

/**
*/
export class CustomContentTypeFieldApi extends AutoController<CustomContentTypeField, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('customcontenttypefield')
        this.includes = new CustomContentTypeFieldIncludes('', '');
    }

}

export default new CustomContentTypeFieldApi();
