/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {DomainCertificateIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A DomainCertificate
*/
export type DomainCertificate = VersionedContent<uint> & {
    domain?: string,
    ready: boolean,
    fileKey?: string,
    expiryUtc?: Date,
    serverId: uint,
    orderUrl?: string,
    status: uint,
    lastPingUtc: Date,
}

/**
*/
export class DomainCertificateApi extends AutoController<DomainCertificate, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('domaincertificate')
        this.includes = new DomainCertificateIncludes('', '');
    }

}

export default new DomainCertificateApi();
