/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {EmailTemplateIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A particular email template.
*/
export type EmailTemplate = VersionedContent<uint> & {
    key?: string,
    name?: string,
    subject?: string,
    bodyJson?: string,
    notes?: string,
    sendFrom?: string,
    emailType: int,
}

/*
*/
export type EmailTestResponse = {
    sent?: boolean,
}

/*
*/
export type EmailTestRequest = {
    templateKey?: string,
    customData?: string,
}

/**
*/
export class EmailTemplateApi extends AutoController<EmailTemplate, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('emailtemplate')
        this.includes = new EmailTemplateIncludes('', '');
    }

    /**
      Sends a test email.
      @param {context} - Api.AvailableEndpoints.XmlDocMember
      @param {mailTest} - Api.AvailableEndpoints.XmlDocMember

    */
    public testEmail = (mailTest: EmailTestRequest): Promise<EmailTestResponse>  => {
        return getText(this.apiUrl + '/test', mailTest)
    }

}

export default new EmailTemplateApi();
