/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {NavMenuIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A particular nav menu.
*/
export type NavMenu = VersionedContent<uint> & {
    key?: string,
    name?: string,
    target?: string,
    order: int,
}

/**
*/
export class NavMenuApi extends AutoController<NavMenu, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('navmenu')
        this.includes = new NavMenuIncludes('', '');
    }

}

export default new NavMenuApi();
