/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {NavMenuItemIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A particular entry within a navigation menu.
*/
export type NavMenuItem = VersionedContent<uint> & {
    navMenuId: uint,
    menuKey?: string,
    parentItemId?: uint,
    bodyJson?: string,
    target?: string,
    iconRef?: string,
    order: int,
}

/**
*/
export class NavMenuItemApi extends AutoController<NavMenuItem, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('navmenuitem')
        this.includes = new NavMenuItemIncludes('', '');
    }

}

export default new NavMenuItemApi();
