/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {PaymentMethodIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A Payment method - this is generally a saved tokenised card.
*/
export type PaymentMethod = VersionedContent<uint> & {
    paymentGatewayId: uint,
    gatewayToken?: string,
    issuer?: string,
    expiryUtc: Date,
    lastUsedUtc: Date,
    paymentMethodTypeId: uint,
    name?: string,
    oneMonthExpiryNotice: boolean,
}

/**
*/
export class PaymentMethodApi extends AutoController<PaymentMethod, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('paymentmethod')
        this.includes = new PaymentMethodIncludes('', '');
    }

}

export default new PaymentMethodApi();
