/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {PermalinkIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A Permalink
*/
export type Permalink = VersionedContent<uint> & {
}

/**
*/
export class PermalinkApi extends AutoController<Permalink, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('permalink')
        this.includes = new PermalinkIncludes('', '');
    }

}

export default new PermalinkApi();
