/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {PriceIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A Price
*/
export type Price = VersionedContent<uint> & {
    name?: string,
    amount: uint,
    currencyCode?: string,
}

/**
*/
export class PriceApi extends AutoController<Price, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('price')
        this.includes = new PriceIncludes('', '');
    }

}

export default new PriceApi();
