/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ProductTemplateIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A ProductTemplate
*/
export type ProductTemplate = VersionedContent<uint> & {
}

/**
*/
export class ProductTemplateApi extends AutoController<ProductTemplate, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('producttemplate')
        this.includes = new ProductTemplateIncludes('', '');
    }

}

export default new ProductTemplateApi();
