/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ProductCategoryIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A ProductCategory
*/
export type ProductCategory = VersionedContent<uint> & {
    name?: string,
    slug?: string,
    description?: string,
    featureRef?: string,
    iconRef?: string,
    legacyId?: string,
    parentId?: uint,
}

/**
*/
export class ProductCategoryApi extends AutoController<ProductCategory, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('productcatgeory')
        this.includes = new ProductCategoryIncludes('', '');
    }

}

export default new ProductCategoryApi();
