/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ProductAttributeIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A ProductAttribute
*/
export type ProductAttribute = VersionedContent<uint> & {
    name?: string,
    productAttributeType: int,
    units?: string,
}

/**
*/
export class ProductAttributeApi extends AutoController<ProductAttribute, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('productattribute')
        this.includes = new ProductAttributeIncludes('', '');
    }

}

export default new ProductAttributeApi();
