/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ProductAttributeGroupIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A group of product attributes. For example, "Dimensions".
            Can be nested in a tree, and a group can be added to multiple parents.
*/
export type ProductAttributeGroup = VersionedContent<uint> & {
    name?: string,
}

/**
*/
export class ProductAttributeGroupApi extends AutoController<ProductAttributeGroup, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('productattributegroup')
        this.includes = new ProductAttributeGroupIncludes('', '');
    }

}

export default new ProductAttributeGroupApi();
