/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ProductQuantityIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  Tracks a product and a quantity of the product.
*/
export type ProductQuantity = VersionedContent<uint> & {
    productId: uint,
    quantity: ulong,
    shoppingCartId: uint,
    subscriptionId: uint,
    purchaseId: uint,
}

/**
*/
export class ProductQuantityApi extends AutoController<ProductQuantity, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('productusage')
        this.includes = new ProductQuantityIncludes('', '');
    }

}

export default new ProductQuantityApi();
