/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ProductAttributeValueIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A ProductAttributeValue
*/
export type ProductAttributeValue = VersionedContent<uint> & {
    productAttributeId: uint,
    value?: string,
}

/**
*/
export class ProductAttributeValueApi extends AutoController<ProductAttributeValue, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('productattributevalue')
        this.includes = new ProductAttributeValueIncludes('', '');
    }

}

export default new ProductAttributeValueApi();
