/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ProductIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A Product
*/
export type Product = VersionedContent<uint> & {
    name?: string,
    isBilledByUsage: boolean,
    billingFrequency: uint,
    minQuantity: ulong,
    descriptionJson?: string,
    featureRef?: string,
    priceStrategy: uint,
    priceId: uint,
    stock?: uint,
    variantOfId: uint,
    tierOfId: uint,
    attributesJson?: string,
}

/**
*/
export class ProductApi extends AutoController<Product, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('product')
        this.includes = new ProductIncludes('', '');
    }

}

export default new ProductApi();
