/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {UserCreatedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {PublishGroupIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A PublishGroup. Created and manipulated by users but doesn't have revisions itself.
*/
export type PublishGroup = UserCreatedContent<uint> & {
    name?: string,
    isPublished: boolean,
    readyForPublishing: boolean,
    autoPublishTimeUtc?: Date,
}

/**
*/
export class PublishGroupApi extends AutoController<PublishGroup, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('publishgroup')
        this.includes = new PublishGroupIncludes('', '');
    }

}

export default new PublishGroupApi();
