/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {RedirectIncludes, ApiIncludes} from './Includes'
import {getJson} from 'UI/Functions/WebRequest'

// Module
/*
  A Redirect
*/
export type Redirect = VersionedContent<uint> & {
    from?: string,
    to?: string,
    permanentRedirect: boolean,
}

/**
*/
export class RedirectApi extends AutoController<Redirect, uint, RedirectIncludes>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('redirect')
        this.includes = new RedirectIncludes();
    }

}

export default new RedirectApi();
