/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {RoleIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A role which defines a set of capabilities to a user who is granted this particular role.
*/
export type Role = VersionedContent<uint> & {
    name?: string,
    key?: string,
    canViewAdmin: boolean,
    isComposite: boolean,
    adminDashboardJson?: string,
    grantRuleJson?: string,
    inheritedRoleId: uint,
    grantRules?: RoleGrantRule[],
}

/**
*/
export class RoleApi extends AutoController<Role, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('role')
        this.includes = new RoleIncludes('', '');
    }

}

/*
*/
export type RoleGrantRule = {
    ruleType: RoleGrantRuleType,
    filterQuery?: string,
    patterns?: String[],
    sameAsRole?: Role,
}

export default new RoleApi();
