/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {ShoppingCartIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A ShoppingCart contains a list of productQuantities.
            A user has a "current" shopping cart associated to them, and when they checkout, the shopping cart is converted to a payment.
*/
export type ShoppingCart = VersionedContent<uint> & {
    status: uint,
}

/**
*/
export class ShoppingCartApi extends AutoController<ShoppingCart, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('shoppingcart')
        this.includes = new ShoppingCartIncludes('', '');
    }

}

export default new ShoppingCartApi();
