/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {UserCreatedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {SubscriptionUsageIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A SubscriptionUsage
*/
export type SubscriptionUsage = UserCreatedContent<uint> & {
    productId: uint,
    subscriptionId: uint,
    maximumUsageToday: uint,
    chargedTimeslotId: uint,
    dateUtc: Date,
}

/**
*/
export class SubscriptionUsageApi extends AutoController<SubscriptionUsage, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('subscriptionusage')
        this.includes = new SubscriptionUsageIncludes('', '');
    }

}

export default new SubscriptionUsageApi();
