/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {TagIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A tag.
            These are the primary taxonomy mechanism; any site content can be grouped up in multiple tags.
*/
export type Tag = VersionedContent<uint> & {
    order: int,
    isPrice: boolean,
    name?: string,
    description?: string,
    featureRef?: string,
    iconRef?: string,
    hexColor?: string,
}

/**
*/
export class TagApi extends AutoController<Tag, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('tag')
        this.includes = new TagIncludes('', '');
    }

}

export default new TagApi();
