/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {TemplateIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A template.
*/
export type Template = VersionedContent<uint> & {
    key?: string,
    title?: string,
    description?: string,
    templateParent: uint,
    baseTemplate?: string,
    templateType: uint,
    moduleGroups?: string,
    bodyJson?: string,
}

/**
*/
export class TemplateApi extends AutoController<Template, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('template')
        this.includes = new TemplateIncludes('', '');
    }

}

export default new TemplateApi();
