/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {TranslationIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A Translation
*/
export type Translation = VersionedContent<uint> & {
    module?: string,
    original?: string,
    translated?: string,
}

/**
*/
export class TranslationApi extends AutoController<Translation, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('translation')
        this.includes = new TranslationIncludes('', '');
    }

    /**
      Requests pre-populate the translations table

    */
    public prePopulate = (): Promise<any>  => {
        return getJson<Record<string, string | number | boolean>>(this.apiUrl + '/prepopulate')
    }

    /**
      Process any pot files into the translations table

    */
    public loadPotFiles = (): Promise<any>  => {
        return getJson<Record<string, string | number | boolean>>(this.apiUrl + '/potfiles')
    }

}

export default new TranslationApi();
