/* * * * * * * | Auto Generated Script, do not edit | * * * * * * * */
// Imports
import {VersionedContent} from './Content'
import {AutoController} from './ApiEndpoints'
import {UserIncludes, ApiIncludes} from './Includes'
// eslint-disable-next-line no-restricted-imports
import {getOne, getList, getJson, getText} from 'UI/Functions/WebRequest'

// Module
/*
  A particular user account.
*/
export type User = VersionedContent<uint> & {
    email?: string,
    emailOptOutFlags: uint,
    emailVerifyToken?: string,
    passwordHash?: string,
    loginAttempts: int,
    failedLoginTimeUtc?: Date,
    firstName?: string,
    lastName?: string,
    fullName?: string,
    lastVisitedUtc: Date,
    loginRevokeCount: uint,
    role: uint,
    privateVerify: long,
    featureRef?: string,
    avatarRef?: string,
    username?: string,
    localeId?: uint,
    passwordReset?: string,
    joinedUtc: Date,
}

/*
*/
export type UserPasswordForgot = {
    email?: string,
}

/*
*/
export type OptionalPassword = {
    password?: string,
}

/*
*/
export type UserLogin = {
    emailOrUsername?: string,
    password?: string,
}

/**
*/
export class UserApi extends AutoController<User, uint>{
    /**
      AutoGenerated, ensures all default CRUD functionality

    */
    public constructor (){
        super('user')
        this.includes = new UserIncludes('', '');
    }

    /**
      POST /v1/user/sendverifyemail/
            Sends the user a new token to verify their email.

    */
    public resendVerificationEmail = (setSession: (s: SessionResponse) => Session, body: UserPasswordForgot): Promise<SessionResponse>  => {
        return getJson<SessionResponse>(this.apiUrl + '/sendverifyemail', body)
        .then((s: SessionResponse) => {
        	setSession(s);
        	return s;
        })
    }

    /**
      POST /v1/user/verify/{userid}/{token}
            Attempts to verify the users email. If a password is supplied, the users password is also set.

    */
    public verifyUser = (setSession: (s: SessionResponse) => Session, userid: uint, token: string, newPassword: OptionalPassword): Promise<SessionResponse>  => {
        return getJson<SessionResponse>(this.apiUrl + '/verify/' + userid + '/' + token + '', newPassword)
        .then((s: SessionResponse) => {
        	setSession(s);
        	return s;
        })
    }

    /**
      Gets the current context.

    */
    public self = (setSession: (s: SessionResponse) => Session): Promise<SessionResponse>  => {
        return getJson<SessionResponse>(this.apiUrl + '/self')
        .then((s: SessionResponse) => {
        	setSession(s);
        	return s;
        })
    }

    /**
      Logs out this user account.

    */
    public logout = (setSession: (s: SessionResponse) => Session): Promise<SessionResponse>  => {
        return getJson<SessionResponse>(this.apiUrl + '/logout')
        .then((s: SessionResponse) => {
        	setSession(s);
        	return s;
        })
    }

    /**
      POST /v1/user/login/
            Attempts to login. Returns either a Context or a LoginResult.

    */
    public login = (body: UserLogin): Promise<any>  => {
        return getJson<Record<string, string | number | boolean>>(this.apiUrl + '/login', body)
    }

    /**
      Impersonate a user by their ID. This is a hard cookie switch. You will loose all admin functionality to make the impersonation as accurate as possible.

    */
    public impersonate = (setSession: (s: SessionResponse) => Session, id: uint): Promise<SessionResponse>  => {
        return getJson<SessionResponse>(this.apiUrl + '/' + id + '/impersonate')
        .then((s: SessionResponse) => {
        	setSession(s);
        	return s;
        })
    }

    /**
      Reverses an impersonation.

    */
    public unpersonate = (setSession: (s: SessionResponse) => Session): Promise<SessionResponse>  => {
        return getJson<SessionResponse>(this.apiUrl + '/unpersonate')
        .then((s: SessionResponse) => {
        	setSession(s);
        	return s;
        })
    }

}

export default new UserApi();
